export {default as HomePage} from "./HomePage";
export {default as Slider} from "./Slider";
export {default as HomePageCard} from "./HomePageCard";
export {default as SliderCategory} from "./SliderCategory";
export {default as SliderProduct} from "./SliderProduct";
export {default as NavBar} from "./NavBar";
export {default as Search} from "./Search";
export {default as Checkout} from "./Checkout";
export {default as ProductPage} from "./ProductPage";
export {default as SearchResults} from "./SearchResults";
export { default as ProductDetails } from "./ProductDetails";
export { default as ProductBadge } from "./ProductBadge";
export { default as ProductRatings} from "./ProductRatings";